general.import = [
  "~/.config/alacritty/base16-chalk.toml"
]

[font]
size = 9.5

[font.normal]
family = "Bitstream Vera Sans Mono"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Control"

[window.padding]
x = 3
y = 3
