[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x505050"
blue = "0xb0b0b0"
cyan = "0xdeaf8f"
green = "0x202020"
magenta = "0xe0e0e0"
red = "0xeda987"
white = "0xf5f5f5"
yellow = "0x303030"

[colors.cursor]
cursor = "0xd0d0d0"
text = "0x151515"

[colors.normal]
black = "0x151515"
blue = "0x6fc2ef"
cyan = "0x12cfc0"
green = "0xacc267"
magenta = "0xe1a3ee"
red = "0xfb9fb1"
white = "0xd0d0d0"
yellow = "0xddb26f"

[colors.primary]
background = "0x151515"
foreground = "0xd0d0d0"

[font]
size = 9.5

[font.normal]
family = "Bitstream Vera Sans Mono"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Control"

[window.padding]
x = 3
y = 3
