general.import = [
  # "~/.config/alacritty/base16-chalk.toml"
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 9.5

[font.normal]
family = "Bitstream Vera Sans Mono"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Control"

[window.padding]
x = 5
y = 5
