# Base16 Chalk - alacritty color config
# Chris Kempson (http://chriskempson.com)

[colors]
draw_bold_text_with_bright_colors = false

# Default colors
[colors.primary]
background = '0x151515'
foreground = '0xd0d0d0'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0x151515'
cursor = '0xd0d0d0'

# Normal colors
[colors.normal]
black = '0x151515'
red = '0xfb9fb1'
green = '0xacc267'
yellow = '0xddb26f'
blue = '0x6fc2ef'
magenta = '0xe1a3ee'
cyan = '0x12cfc0'
white = '0xd0d0d0'

# Bright colors
[colors.bright]
black = '0x505050'
red = '0xeda987'
green = '0x202020'
yellow = '0x303030'
blue = '0xb0b0b0'
magenta = '0xe0e0e0'
cyan = '0xdeaf8f'
white = '0xf5f5f5'
